app/utils/urls.py
from urllib.parse import urlparse
from flask import request


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(target)
    return test_url.netloc == "" or test_url.netloc == ref_url.netloc

app/routes/artist.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
    send_file,
    session,
)
from app.utils.decorators import role_required
from app.models import (
    fetch_list_artist,
    create_artist,
    create_artists_bulk,
    get_artist_by_id,
    update_artist,
    fetch_list_music,
    get_all_artists,
    get_artist_by_user_id,
    delete_artist,
    delete_user,
)
from app.services.artist import validate_artist
from app.utils.exceptions import ValidationError
import io
import csv

bp = Blueprint("artist", __name__, url_prefix="/artist")


@bp.route("", methods=("GET",))
@role_required("super_admin", "artist_manager")
def list_artist_view():
    page = request.args.get("page", 1, type=int)
    page_size = request.args.get("page_size", 10, type=int)

    data = fetch_list_artist(page, page_size)
    print(data)
    return render_template(
        "artist/list_artist.j2",
        template_name="artist/list_artist.j2",
        **data,
    )


@bp.route("/create", methods=("GET", "POST"))
@role_required("super_admin", "artist_manager")
def create_artist_view():
    if request.method == "POST":
        try:
            validate_artist(request.form)
            create_artist(request.form)

            flash("Artist created successfully", "success")
            return redirect(url_for("artist.list_artist_view"))
        except ValidationError as e:
            print(f"validation error {e.errors}")
            flash("Fail to update artist", "error")

            return render_template(
                "artist/form_artist.j2",
                errors=e.errors,
                form=request.form,
            )
    return render_template("artist/form_artist.j2")


@bp.route("/file/create", methods=["POST"])
@role_required("super_admin", "artist_manager")
def create_artist_from_file():
    REQUIRED_COLUMNS = {
        "name",
        "dob",
        "gender",
        "address",
        "first_release_year",
        "no_of_albums",
    }
    file = request.files.get("file")
    if not file:
        flash("Please Upload File", "error")
        return redirect(url_for("artist.list_artist_view"))
    try:
        stream = io.StringIO(file.stream.read().decode("UTF8"), newline=None)
        csv_reader = csv.DictReader(stream)
        csv_columns = set(csv_reader.fieldnames or [])

        missing_columns = REQUIRED_COLUMNS - csv_columns
        if missing_columns:
            flash(f"Missing columns: {', '.join(missing_columns)}", "error")
            return redirect(url_for("artist.list_artist_view"))

        artists_to_insert = []

        for row in csv_reader:
            if not row.get("name"):
                continue

            artists_to_insert.append(
                {
                    "name": row.get("name"),
                    "dob": row.get("dob"),
                    "gender": row.get("gender"),
                    "address": row.get("address"),
                    "first_release_year": row.get("first_release_year"),
                    "no_of_albums": row.get("no_of_albums"),
                }
            )

        if not artists_to_insert:
            flash("No valid records found.", "error")
            return redirect(url_for("artist.list_artist_view"))

        create_artists_bulk(artists_to_insert)

        flash(f"{len(artists_to_insert)} artists created successfully!", "success")
        return redirect(url_for("artist.list_artist_view"))

    except Exception as e:
        flash(str(e), "error")
        return redirect(url_for("artist.list_artist_view"))


@bp.route("/file/export", methods=["GET"])
@role_required("super_admin", "artist_manager")
def export_artist_to_file():
    try:
        artists = get_all_artists()

        output = io.StringIO()
        writer = csv.writer(output)

        # No ID column
        writer.writerow(
            [
                "name",
                "dob",
                "gender",
                "address",
                "first_release_year",
                "no_of_albums",
            ]
        )

        for artist in artists:
            writer.writerow(
                [
                    artist["name"],
                    artist["dob"],
                    artist["gender"],
                    artist["address"],
                    artist["first_release_year"],
                    artist["no_of_albums"],
                ]
            )

        output.seek(0)

        return send_file(
            io.BytesIO(output.getvalue().encode("utf-8")),
            mimetype="text/csv",
            as_attachment=True,
            download_name="artists_export.csv",
        )

    except Exception as e:
        flash(str(e), "error")
        return redirect(url_for("artist.list_artist_view"))


@bp.route("/<int:artist_id>", methods=("GET",))
@role_required("super_admin", "artist_manager")
def detail_artist_view(artist_id: int):
    page = request.args.get("page", 1, type=int)
    page_size = request.args.get("page_size", 10, type=int)

    artist = get_artist_by_id(artist_id)
    music = fetch_list_music(artist_id, page, page_size)
    if artist:
        return render_template(
            "artist/detail_artist.j2",
            artist_id=artist["id"],
            artist=artist,
            music=music,
        )
    return render_template("404.j2")


@bp.route("user/<int:user_id>", methods=("GET",))
@role_required("artist")
def get_artist_by_user(user_id: int):
    page = request.args.get("page", 1, type=int)
    page_size = request.args.get("page_size", 10, type=int)

    artist = get_artist_by_user_id(user_id)
    if artist:
        music = fetch_list_music(artist["id"], page, page_size)
        return render_template(
            "artist/detail_artist.j2",
            artist_id=artist["id"],
            artist=artist,
            music=music,
        )
    return render_template("404.j2")


@bp.route("/<int:artist_id>/update", methods=("GET", "POST"))
@role_required("super_admin", "artist_manager")
def update_artist_view(artist_id):
    artist = get_artist_by_id(artist_id)
    if request.method == "POST":
        print()
        try:
            validate_artist(request.form)
            update_artist(request.form)

            flash("Artist updated successfully", "success")
            return redirect(url_for("artist.list_artist_view"))
        except ValidationError as e:
            print(f"validation error {e.errors}")
            flash("Fail to update artist", "error")

            return render_template(
                "artist/form_artist.j2",
                errors=e.errors,
                artist_id=artist["id"],
                form=request.form,
            )

    return render_template("artist/form_artist.j2", artist_id=artist["id"], form=artist)


@bp.route("/<int:artist_id>/delete", methods=("POST",))
@role_required("super_admin", "artist_manager")
def delete_artist_view(artist_id):
    try:
        artist = get_artist_by_id(artist_id)

        if not artist:
            flash("Artist not found.", "error")
            return redirect(url_for("artist.list_artist_view"))
        if (
            session.get("role") == "artist_manager"
            and artist.get("user_id") is not None
        ):
            flash("You cannot delete an artist who has a user account.", "error")
            return redirect(url_for("artist.list_artist_view"))
        delete_artist(artist_id)
        delete_user(artist.get("user_id"))
        flash("Artist deleted successfully.", "success")

    except ValueError as e:
        flash(str(e), "error")

    return redirect(url_for("artist.list_artist_view"))

app/routes/music.py
from flask import render_template, request, flash, redirect, url_for, Blueprint
from app.utils.decorators import role_required
from app.utils.exceptions import ValidationError
from app.models import create_music, delete_music, get_music_by_id, update_music
from app.services.music import validate_music
from app.utils.urls import is_safe_url

bp = Blueprint("music", __name__, url_prefix="/music")


@bp.route("/artist/<int:artist_id>/create", methods=("GET", "POST"))
@role_required("super_admin", "artist_manager", "artist")
def create_music_for_artist_view(artist_id):
    if request.method == "POST":
        try:
            validate_music(request.form)
            create_music(request.form)
            flash("Music created successfully", "success")
            next_endpoint = request.form.get("next")
            if next_endpoint and is_safe_url(next_endpoint):
                try:
                    return redirect(next_endpoint)
                except Exception as e:
                    print(f"error: {e}")
            return redirect(url_for("artist.detail_artist_view", artist_id=artist_id))
        except ValidationError as e:
            flash("Fail to update artist", "error")

            return render_template(
                "music/form_music_with_artist_id.j2",
                next=next_endpoint,
                errors=e.errors,
                form=request.form,
            )
    next_endpoint = request.args.get("next")
    return render_template(
        "music/form_music_with_artist_id.j2", artist_id=artist_id, next=next_endpoint
    )


@bp.route("/<int:music_id>/update", methods=("GET", "POST"))
@role_required("super_admin", "artist_manager", "artist")
def update_music_view(music_id):
    music = get_music_by_id(music_id)
    if request.method == "POST":
        try:
            validate_music(request.form)
            update_music(request.form)

            flash("Music updated successfully", "success")
            next_endpoint = request.form.get("next")
            if next_endpoint and is_safe_url(next_endpoint):
                try:
                    return redirect(next_endpoint)
                except Exception as e:
                    print(f"error: {e}")
            return redirect(
                url_for("artist.detail_artist_view", artist_id=music["artist_id"])
            )
        except ValidationError as e:
            flash("Fail to update music", "error")

            return render_template(
                "music/form_music_with_artist_id.j2",
                errors=e.errors,
                music_id=music["id"],
                form=request.form,
            )
    next_endpoint = request.args.get("next")
    return render_template(
        "music/form_music_with_artist_id.j2",
        music_id=music_id,
        artist_id=music["artist_id"],
        form=music,
        next=next_endpoint,
    )


@bp.route("/<int:music_id>/delete", methods=("POST",))
@role_required("super_admin", "artist_manager", "artist")
def delete_music_view(music_id):
    if request.method == "POST":
        music = get_music_by_id(music_id)
        try:
            delete_music(music_id)
            flash("Artist deleted successfully", "success")
        except ValueError as e:
            flash(str(e), "error")
    next = request.args.get("next")
    if next and is_safe_url(next):
        return redirect(next)
    return redirect(url_for("artist.detail_artist_view", artist_id=music["artist_id"]))

app/templates/artist/detail_artist.j2
{% extends "base.j2" %}
{% block title %} Artist Detail {% endblock %}

{% block body %}
<div class="flex items-center justify-center py-10">
    <div class="bg-white shadow-xl rounded-2xl w-full max-w-3xl p-8">

        <h2 class="text-2xl font-bold text-center mb-8 text-gray-800">
            Artist Details
        </h2>

        <div class="grid grid-cols-2 gap-6">

            <div>
                <p class="text-sm text-gray-500">Full Name</p>
                <p class="text-lg font-medium text-gray-800">
                    {{ artist.name }}
                </p>
            </div>

            <div>
                <p class="text-sm text-gray-500">Date of Birth</p>
                <p class="text-lg font-medium text-gray-800">
                    {{ artist.dob }}
                </p>
            </div>

            <div>
                <p class="text-sm text-gray-500">First Release Year</p>
                <p class="text-lg font-medium text-gray-800">
                    {{ artist.first_release_year }}
                </p>
            </div>
            <div>
                <p class="text-sm text-gray-500">Number of Albums</p>
                <p class="text-lg font-medium text-gray-800">
                    {{ artist.no_of_albums }}
                </p>
            </div>

            <div>
                <p class="text-sm text-gray-500">Gender</p>
                <p class="text-lg font-medium text-gray-800">
                    {% if artist.gender == 'm' %}
                    Male
                    {% elif artist.gender == 'f' %}
                    Female
                    {% elif artist.gender == 'o' %}
                    Other
                    {% else %}
                    -
                    {% endif %}
                </p>
            </div>

            <div>
                <p class="text-sm text-gray-500">Address</p>
                <p class="text-lg font-medium text-gray-800">
                    {{ artist.address }}
                </p>
            </div>

        </div>
        {% if session.get("role") in ["super_admin","artist_manager"] %}
        <div class="mt-10 flex justify-evenly">
            <a href="{{ url_for('artist.list_artist_view') }}"
                class="px-6 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition">
                Back
            </a>

            <a href="{{ url_for('artist.update_artist_view', artist_id=artist.id) }}"
                class="px-6 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition">
                Edit
            </a>
            <form method="POST" action="{{ url_for('artist.delete_artist_view', artist_id=artist.id) }}"
                onsubmit="return confirm('Are you sure you want to delete this artist?');">

                <button type="submit" class="px-6 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition">
                    Delete
                </button>
            </form>
        </div>
        {% endif %}
    </div>
</div>
<div class="flex items-center justify-center py-10">
    <div class="bg-white shadow-xl rounded-2xl w-full max-w-3xl p-8">
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 space-y-3 sm:space-y-0">
            <h2 class="text-2xl font-bold text-gray-800">
                Music
            </h2>

            <div class="flex flex-wrap items-center gap-3">
                <span class="text-sm text-gray-500">
                    Showing {{ music.musics|length }} of {{ music.total }} music
                </span>

                <a href="{{ url_for('music.create_music_for_artist_view', artist_id=artist.id, next=request.path) }}"
                    class="px-3 py-1 text-sm bg-gray-700 hover:bg-gray-900 text-white rounded-lg transition inline-flex items-center justify-center">
                    Add Music
                </a>
            </div>
        </div>
        <div class="overflow-x-auto">
            <table class="min-w-full border border-gray-200 rounded-sm overflow-hidden">
                <thead class="bg-gray-100 text-gray-600 text-sm uppercase tracking-wider">
                    <tr>
                        <th class="px-6 py-3 text-left">Title</th>
                        <th class="px-6 py-3 text-left">Album Name</th>
                        <th class="px-6 py-3 text-left">Genre</th>
                        <th class="px-6 py-3 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 text-gray-700">
                    {% for music in music.musics %}

                    <tr class="hover:bg-gray-50 transition duration-150">
                        <td class="px-6 py-4 font-medium">
                            {{ music.title }}
                        </td>
                        <td class="px-6 py-4 font-medium">
                            {{ music.album_name }}
                        </td>

                        <td class="px-6 py-4">
                            {{ music.genre }}
                        </td>

                        <td class="px-6 py-4 text-center">
                            <div class="flex justify-center space-x-3">

                                <a href="{{ url_for('music.update_music_view', music_id=music.id, next=request.path) }}"
                                    class="px-3 py-1 text-sm bg-yellow-500 hover:bg-yellow-600 text-white rounded-lg transition">
                                    Edit
                                </a>

                                <form method="POST"
                                    action="{{ url_for('music.delete_music_view', music_id=music.id, next=request.path) }}"
                                    onsubmit="return confirm('Are you sure you want to delete this artist?');">

                                    <button type="submit"
                                        class="px-3 py-1 text-sm bg-red-500 hover:bg-red-600 text-white rounded-lg transition">
                                        Delete
                                    </button>
                                </form>

                            </div>
                        </td>

                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="4" class="text-center py-6 text-gray-500">
                            No music found.
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="flex justify-between items-center mt-6">

            {% if music.page > 1 %}
            <a href="{{ url_for('artist.detail_artist_view',artist_id=artist.id, page=music.page-1, page_size=music.page_size) }}"
                class="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-700 rounded-lg transition">
                Previous
            </a>
            {% else %}
            <div></div>
            {% endif %}

            <span class="text-sm text-gray-600">
                Page {{ music.page }} of {{ music.total_pages }}
            </span>

            {% if music.page < music.total_pages %} <a
                href="{{ url_for('artist.detail_artist_view', artist_id=artist.id,page=music.page+1, page_size=music.page_size) }}"
                class="px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-lg transition">
                Next
                </a>
                {% else %}
                <div></div>
                {% endif %}

        </div>
    </div>
</div>
{% endblock %}

app/templates/artist/list_artist.j2
{% extends "base.j2" %}
{% block title %} User List {% endblock %}

{% block body %}
<div class="min-h-screen bg-gray-100 py-10 px-6">
    <div class="max-w-6xl mx-auto bg-white shadow-xl rounded-lg p-8">

        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 space-y-3 sm:space-y-0">
            <h2 class="text-2xl font-bold text-gray-800">
                Artist
            </h2>

            <div class="flex flex-wrap items-center gap-3">
                <span class="text-sm text-gray-500">
                    Showing {{ artists|length }} of {{ total }} artists
                </span>

                <button type="button" onclick="openModal()"
                    class="px-3 py-1.5 text-sm bg-gray-700 hover:bg-gray-900 text-white rounded-lg transition inline-flex items-center justify-center">
                    Bulk Add Artist
                </button>

                <a href="{{ url_for('artist.create_artist_view', next=request.path) }}"
                    class="px-3 py-1.5 text-sm bg-gray-700 hover:bg-gray-900 text-white rounded-lg transition inline-flex items-center justify-center">
                    Add Artist
                </a>

                <a href="{{ url_for('artist.export_artist_to_file') }}"
                    class="px-3 py-1.5 text-sm bg-green-600 hover:bg-green-700 text-white rounded-lg transition inline-flex items-center justify-center">
                    Export Artists
                </a>
            </div>
        </div>

        <div id="bulkModal" class="fixed inset-0 bg-black bg-opacity-50 hidden items-center justify-center z-50">

            <div class="bg-white rounded-2xl shadow-xl w-full max-w-md p-6 relative">

                <button onclick="closeModal()" class="absolute top-3 right-3 text-gray-500 hover:text-gray-800 text-xl">
                    &times;
                </button>

                <h2 class="text-xl font-semibold mb-4">Import Artists (CSV)</h2>

                <form action="{{ url_for('artist.create_artist_from_file') }}" method="POST"
                    enctype="multipart/form-data" class="space-y-4">

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">
                            Upload CSV File
                        </label>

                        <input type="file" name="file" accept=".csv" required class="block w-full text-sm text-gray-700
                              file:mr-4 file:py-2 file:px-4
                              file:rounded-lg file:border-0
                              file:text-sm file:font-semibold
                              file:bg-gray-700 file:text-white
                              hover:file:bg-gray-900
                              border border-gray-300 rounded-lg p-2" />
                    </div>

                    <div class="flex justify-end space-x-2">
                        <button type="button" onclick="closeModal()"
                            class="px-4 py-2 bg-gray-300 hover:bg-gray-400 rounded-lg text-sm">
                            Cancel
                        </button>

                        <button type="submit"
                            class="px-4 py-2 bg-gray-700 hover:bg-gray-500 text-white rounded-lg text-sm">
                            Import
                        </button>
                    </div>

                </form>
            </div>
        </div>

        <div class="overflow-x-auto">
            <table class="min-w-full border border-gray-200 rounded-sm overflow-hidden">
                <thead class="bg-gray-100 text-gray-600 text-sm uppercase tracking-wider">
                    <tr>
                        <th class="px-6 py-3 text-left">Name</th>
                        <th class="px-6 py-3 text-left">First Release Year</th>
                        <th class="px-6 py-3 text-left">Address</th>
                        <th class="px-6 py-3 text-center">Actions</th>
                    </tr>
                </thead>

                <tbody class="divide-y divide-gray-200 text-gray-700">
                    {% for artist in artists %}
                    <tr class="hover:bg-gray-50 transition duration-150">
                        <td class="px-6 py-4 font-medium">
                            {{ artist.name }}
                        </td>
                        <td class="px-6 py-4 font-medium">
                            {{ artist.first_release_year }}
                        </td>

                        <td class="px-6 py-4">
                            {{ artist.address }}
                        </td>

                        <td class="px-6 py-4 text-center">
                            <div class="flex justify-center space-x-3">

                                <a href="{{ url_for('artist.detail_artist_view', artist_id=artist.id) }} "
                                    class="px-3 py-1 text-sm bg-green-400 hover:bg-green-500 text-white rounded-lg transition">
                                    Detail
                                </a>

                                <a href="{{ url_for('artist.update_artist_view', artist_id=artist.id) }}"
                                    class="px-3 py-1 text-sm bg-yellow-500 hover:bg-yellow-600 text-white rounded-lg transition">
                                    Edit
                                </a>

                                <form method="POST"
                                    action="{{ url_for('artist.delete_artist_view', artist_id=artist.id) }}"
                                    onsubmit="return confirm('Are you sure you want to delete this artist? If user exists it might be delete as well');">

                                    <button type="submit"
                                        class="px-3 py-1 text-sm bg-red-500 hover:bg-red-600 text-white rounded-lg transition">
                                        Delete
                                    </button>
                                </form>

                            </div>
                        </td>

                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="4" class="text-center py-6 text-gray-500">
                            No artists found.
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="flex justify-between items-center mt-6">

            {% if page > 1 %}
            <a href="{{ url_for('artist.list_artist_view', page=page-1, page_size=page_size) }}"
                class="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-700 rounded-lg transition">
                Previous
            </a>
            {% else %}
            <div></div>
            {% endif %}

            <span class="text-sm text-gray-600">
                Page {{ page }} of {{ total_pages }}
            </span>

            {% if page < total_pages %} <a
                href="{{ url_for('artist.list_artist_view', page=page+1, page_size=page_size) }}"
                class="px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-lg transition">
                Next
                </a>
                {% else %}
                <div></div>
                {% endif %}

        </div>
    </div>
</div>
<script>
    function openModal() {
        const modal = document.getElementById('bulkModal');
        modal.classList.remove('hidden');
        modal.classList.add('flex');
    }

    function closeModal() {
        const modal = document.getElementById('bulkModal');
        modal.classList.add('hidden');
        modal.classList.remove('flex');
    }
</script>
{% endblock %}