app/utils/urls.py
from urllib.parse import urlparse
from flask import request


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(target)
    return test_url.netloc == "" or test_url.netloc == ref_url.netloc

app/routes/artist.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
    send_file,
    session,
)
from app.utils.decorators import role_required
from app.models import (
    fetch_list_artist,
    create_artist,
    create_artists_bulk,
    get_artist_by_id,
    update_artist,
    fetch_list_music,
    get_all_artists,
    get_artist_by_user_id,
    delete_artist,
    delete_user,
)
from app.services.artist import validate_artist
from app.utils.exceptions import ValidationError
import io
import csv

bp = Blueprint("artist", __name__, url_prefix="/artist")


@bp.route("", methods=("GET",))
@role_required("super_admin", "artist_manager")
def list_artist_view():
    page = request.args.get("page", 1, type=int)
    page_size = request.args.get("page_size", 10, type=int)

    data = fetch_list_artist(page, page_size)
    print(data)
    return render_template(
        "artist/list_artist.j2",
        template_name="artist/list_artist.j2",
        **data,
    )


@bp.route("/create", methods=("GET", "POST"))
@role_required("super_admin", "artist_manager")
def create_artist_view():
    if request.method == "POST":
        try:
            validate_artist(request.form)
            create_artist(request.form)

            flash("Artist created successfully", "success")
            return redirect(url_for("artist.list_artist_view"))
        except ValidationError as e:
            print(f"validation error {e.errors}")
            flash("Fail to update artist", "error")

            return render_template(
                "artist/form_artist.j2",
                errors=e.errors,
                form=request.form,
            )
    return render_template("artist/form_artist.j2")


@bp.route("/file/create", methods=["POST"])
@role_required("super_admin", "artist_manager")
def create_artist_from_file():
    REQUIRED_COLUMNS = {
        "name",
        "dob",
        "gender",
        "address",
        "first_release_year",
        "no_of_albums",
    }
    file = request.files.get("file")
    if not file:
        flash("Please Upload File", "error")
        return redirect(url_for("artist.list_artist_view"))
    try:
        stream = io.StringIO(file.stream.read().decode("UTF8"), newline=None)
        csv_reader = csv.DictReader(stream)
        csv_columns = set(csv_reader.fieldnames or [])

        missing_columns = REQUIRED_COLUMNS - csv_columns
        if missing_columns:
            flash(f"Missing columns: {', '.join(missing_columns)}", "error")
            return redirect(url_for("artist.list_artist_view"))

        artists_to_insert = []

        for row in csv_reader:
            if not row.get("name"):
                continue

            artists_to_insert.append(
                {
                    "name": row.get("name"),
                    "dob": row.get("dob"),
                    "gender": row.get("gender"),
                    "address": row.get("address"),
                    "first_release_year": row.get("first_release_year"),
                    "no_of_albums": row.get("no_of_albums"),
                }
            )

        if not artists_to_insert:
            flash("No valid records found.", "error")
            return redirect(url_for("artist.list_artist_view"))

        create_artists_bulk(artists_to_insert)

        flash(f"{len(artists_to_insert)} artists created successfully!", "success")
        return redirect(url_for("artist.list_artist_view"))

    except Exception as e:
        flash(str(e), "error")
        return redirect(url_for("artist.list_artist_view"))


@bp.route("/file/export", methods=["GET"])
@role_required("super_admin", "artist_manager")
def export_artist_to_file():
    try:
        artists = get_all_artists()

        output = io.StringIO()
        writer = csv.writer(output)

        # No ID column
        writer.writerow(
            [
                "name",
                "dob",
                "gender",
                "address",
                "first_release_year",
                "no_of_albums",
            ]
        )

        for artist in artists:
            writer.writerow(
                [
                    artist["name"],
                    artist["dob"],
                    artist["gender"],
                    artist["address"],
                    artist["first_release_year"],
                    artist["no_of_albums"],
                ]
            )

        output.seek(0)

        return send_file(
            io.BytesIO(output.getvalue().encode("utf-8")),
            mimetype="text/csv",
            as_attachment=True,
            download_name="artists_export.csv",
        )

    except Exception as e:
        flash(str(e), "error")
        return redirect(url_for("artist.list_artist_view"))


@bp.route("/<int:artist_id>", methods=("GET",))
@role_required("super_admin", "artist_manager")
def detail_artist_view(artist_id: int):
    page = request.args.get("page", 1, type=int)
    page_size = request.args.get("page_size", 10, type=int)

    artist = get_artist_by_id(artist_id)
    music = fetch_list_music(artist_id, page, page_size)
    if artist:
        return render_template(
            "artist/detail_artist.j2",
            artist_id=artist["id"],
            artist=artist,
            music=music,
        )
    return render_template("404.j2")


@bp.route("user/<int:user_id>", methods=("GET",))
@role_required("artist")
def get_artist_by_user(user_id: int):
    page = request.args.get("page", 1, type=int)
    page_size = request.args.get("page_size", 10, type=int)

    artist = get_artist_by_user_id(user_id)
    if artist:
        music = fetch_list_music(artist["id"], page, page_size)
        return render_template(
            "artist/detail_artist.j2",
            artist_id=artist["id"],
            artist=artist,
            music=music,
        )
    return render_template("404.j2")


@bp.route("/<int:artist_id>/update", methods=("GET", "POST"))
@role_required("super_admin", "artist_manager")
def update_artist_view(artist_id):
    artist = get_artist_by_id(artist_id)
    if request.method == "POST":
        print()
        try:
            validate_artist(request.form)
            update_artist(request.form)

            flash("Artist updated successfully", "success")
            return redirect(url_for("artist.list_artist_view"))
        except ValidationError as e:
            print(f"validation error {e.errors}")
            flash("Fail to update artist", "error")

            return render_template(
                "artist/form_artist.j2",
                errors=e.errors,
                artist_id=artist["id"],
                form=request.form,
            )

    return render_template("artist/form_artist.j2", artist_id=artist["id"], form=artist)


@bp.route("/<int:artist_id>/delete", methods=("POST",))
@role_required("super_admin", "artist_manager")
def delete_artist_view(artist_id):
    try:
        artist = get_artist_by_id(artist_id)

        if not artist:
            flash("Artist not found.", "error")
            return redirect(url_for("artist.list_artist_view"))
        if (
            session.get("role") == "artist_manager"
            and artist.get("user_id") is not None
        ):
            flash("You cannot delete an artist who has a user account.", "error")
            return redirect(url_for("artist.list_artist_view"))
        delete_artist(artist_id)
        delete_user(artist.get("user_id"))
        flash("Artist deleted successfully.", "success")

    except ValueError as e:
        flash(str(e), "error")

    return redirect(url_for("artist.list_artist_view"))

app/routes/dashboard.py
from app.utils.decorators import login_required
from flask import render_template, session
from app.models import dashboard_data


def register_dashboard_routes(app):

    @app.route("/dashboard")
    @login_required
    def dashboard():
        data = {}
        if session.get("role") in ["super_admin", "artist_manager"]:
            data = dashboard_data()
        return render_template("dashboard.j2", data=data)

app/templates/404.j2
{% extends "base.j2" %}
{% block title %} 404 Not Found {% endblock %}
{% block body %}
<div class="min-h-screen flex items-center justify-center  py-10">
    <h1>No Data found</h1>
</div>
{% endblock %}

app/templates/base.j2
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static', filename='style.css' ) }}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <script src="{{ url_for('static', filename='main.js' ) }}">
    </script>
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    {% include "./components/top_nav.j2" %}
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div id="flash-container" class="fixed bottom-5 right-5 space-y-2 z-50">
        {% for category, message in messages %}
        <div class="
          flash-message
          px-4 py-2 rounded shadow
          text-white font-semibold
          {% if category == 'success' %} bg-green-500 {% endif %}
          {% if category == 'error' %} bg-red-500 {% endif %}
          {% if category == 'info' %} bg-blue-500 {% endif %}
        ">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <div>
        {% block body %}{% endblock %}
    </div>
</body>

</html>

app/templates/dashboard.j2
{% extends "base.j2" %}

{% block title %} Dashboard {% endblock %}

{% block body %}
<div class="container mx-auto p-6">
    {% if session.get("role") == "artist" %}
    <div class="text-xl font-semibold text-center">Welcome to Music App</div>
    <p class="text-center">Thank you for using app</p>

    <div class="text-center my-3">
        <a class="bg-gray-700 hover:bg-gray-500 text-white px-3 py-1 rounded"
            href="{{ url_for('artist.get_artist_by_user', user_id=session.get('user_id')) }}">View Profile</a>
    </div>
    {% else %}
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
        {% if session.get('role') == "super_admin" %}
        <div class="bg-white shadow rounded-lg p-6 flex flex-col items-center justify-center">
            <div class="text-gray-500 text-sm">Total Users</div>
            <div class="text-2xl font-bold">{{ data.total_users }}</div>
        </div>
        {% endif %}

        <div class="bg-white shadow rounded-lg p-6 flex flex-col items-center justify-center">
            <div class="text-gray-500 text-sm">Total Artists</div>
            <div class="text-2xl font-bold">{{ data.total_artists }}</div>
        </div>

        <div class="bg-white shadow rounded-lg p-6 flex flex-col items-center justify-center">
            <div class="text-gray-500 text-sm">Total Music</div>
            <div class="text-2xl font-bold">{{ data.total_music }}</div>
        </div>
    </div>
    {% endif %}
</div>

<script>
    // Optional: add JS interactivity if needed
</script>
{% endblock %}